name = "cloudflare-workers"
type = "webpack"
account_id = "08bf68295952bbf06870b876cdf80ef3" # put your account_id here
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv_namespaces = [
    { binding = "BOSSES", preview_id = "722c9229c21f4d17a060f70838e5ec70" } # put your BOSSES kv_id here
]